### PR TITLE
Update bundler and tests

### PR DESCRIPTION
**Pull request by zerebubuth**
* Updated bundle versions to latest.
* Added dependency on minitest.
* Updated code to match latest minitest API.
* Fixed some code as suggested by rubocop.

Note that two tests are still failing, as reported in #5, although the tests are now running without extra warnings.

### CODE REVIEW

**Comment by gravitystorm** [comment]
LGTM, although I haven't run any of the code myself.

Is this code still being used for something? I'm surprised to see any activity here, 5.5 years after the licence change was completed.

**Comment by zerebubuth** [comment]
Thanks!

I'm surprised, too. But I think there's a bunch of logic that we worked through as part of the license change which is still useful for editing out vandalism or redacting dodgy changes. There's probably a large amount of code which is superfluous, though.

**Comment by naoliv** [comment]
I am using your code to redact some big changesets :-)

**Comment by zerebubuth** [comment]
Wow, that's cool! Good luck. Please be careful, though - the code was written for a very specific case at a specific point in time, so there's a fair chance that some assumptions which were true for the license change and for common tagging usage at the time might not be true any longer.

**Pull request merged**
